kind: Pod
apiVersion: v1
metadata:
  name: nimbus
  labels:
    name: nimbus
spec:
  containers:
  - name: nimbus
    image: nubunto/storm-nimbus:2.0.0
    imagePullPolicy: Always
    ports:
    - containerPort: 6627
    resources:
      limits:
        cpu: 100m
